name: Run Tests and Upload Coverage

on:
  push:
    branches: [ dev ]
  #pull_request:
  #  branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          cd frontend && npm install
          cd ../backend && npm install
          cd ..

      - name: Run tests with coverage (frontend + backend)
        run: |
          # Frontend
          cd frontend
          npx jest --coverage --coverageDirectory=../coverage/frontend
          cd ..

          # Backend
          cd backend
          npx jest --coverage --coverageDirectory=../coverage/backend
          cd ..

      - name: Merge coverage reports
        run: |
          npm install -g lcov-result-merger
          lcov-result-merger 'coverage/**/lcov.info' > coverage/lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}   # Only needed for private repos, safe to keep
          files: coverage/lcov.info
          flags: unittests
          fail_ci_if_error: true
