name: Lighthouse

on:
  workflow_run:
    workflows: ["Build and deploy Node.js app to Azure Web App - witsquest"]
    types: [completed]

jobs:
  lighthouse:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Wait for site to be live (warm-up)
        run: |
          URL="https://witsquest-hjggaxgwfgbeh0gk.brazilsouth-01.azurewebsites.net"
          for i in {1..30}; do
            code=$(curl -sk -o /dev/null -w "%{http_code}" "$URL")
            echo "Status: $code"
            if [ "$code" = "200" ] || [ "$code" = "301" ] || [ "$code" = "302" ]; then
              break
            fi
            sleep 5
          done

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Lighthouse CI
        run: npm i -g @lhci/cli@0.13.x

      # --- Desktop run ---
      - name: Run Lighthouse (desktop)
        run: |
          lhci autorun \
            --collect.url=https://witsquest-hjggaxgwfgbeh0gk.brazilsouth-01.azurewebsites.net/ \
            --collect.settings.preset=desktop \
            --collect.numberOfRuns=3 \
            --collect.settings.chromeFlags="--no-sandbox" \
            --upload.target=temporary-public-storage
      - name: Save desktop reports
        if: always()
        run: |
          mkdir -p lighthouse-reports/desktop
          cp -r .lighthouseci/* lighthouse-reports/desktop/ || true
          rm -rf .lighthouseci/* || true

      # --- Mobile run ---
      - name: Run Lighthouse (mobile)
        run: |
          lhci autorun \
            --collect.url=https://witsquest-hjggaxgwfgbeh0gk.brazilsouth-01.azurewebsites.net/ \
            --collect.settings.preset=mobile \
            --collect.numberOfRuns=3 \
            --collect.settings.chromeFlags="--no-sandbox" \
            --upload.target=temporary-public-storage
      - name: Save mobile reports
        if: always()
        run: |
          mkdir -p lighthouse-reports/mobile
          cp -r .lighthouseci/* lighthouse-reports/mobile/ || true

      - name: Upload artifact (desktop + mobile)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: lighthouse-reports
