name: Lighthouse

on:
  # Run automatically after your deploy workflow completes
  workflow_run:
    workflows: ["Build and deploy Node.js app to Azure Web App - witsquest"]
    types: [completed]
    branches: [production]

  # Optional: let you run it manually from the Actions tab
  workflow_dispatch:

jobs:
  lighthouse:
    # Run if the deploy succeeded, or if manually dispatched
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      BASE_URL: https://witsquest-hjggaxgwfgbeh0gk.brazilsouth-01.azurewebsites.net

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Chrome reliably for Lighthouse
      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Wait for site to be live (warm-up)
        run: |
          for i in {1..30}; do
            code=$(curl -sk -o /dev/null -w "%{http_code}" "$BASE_URL")
            echo "Attempt $i: $code"
            if [ "$code" = "200" ] || [ "$code" = "301" ] || [ "$code" = "302" ]; then
              break
            fi
            sleep 5
          done

      - name: Install Lighthouse CI
        run: npm i -g @lhci/cli@0.13.x

      # ----- Desktop run -----
      - name: Run Lighthouse (desktop)
        run: |
          lhci autorun \
            --collect.url="$BASE_URL/" \
            --collect.numberOfRuns=3 \
            --collect.settings.preset=desktop \
            --collect.settings.chromePath="${{ steps.chrome.outputs.chrome-path }}" \
            --collect.settings.chromeFlags="--no-sandbox" \
            --upload.target=temporary-public-storage
      - name: Save desktop reports
        if: always()
        run: |
          mkdir -p lighthouse-reports/desktop
          cp -r .lighthouseci/* lighthouse-reports/desktop/ || true
          rm -rf .lighthouseci/* || true

      # ----- Mobile run -----
      - name: Run Lighthouse (mobile)
        run: |
          lhci autorun \
            --collect.url="$BASE_URL/" \
            --collect.numberOfRuns=3 \
            --collect.settings.preset=mobile \
            --collect.settings.chromePath="${{ steps.chrome.outputs.chrome-path }}" \
            --collect.settings.chromeFlags="--no-sandbox" \
            --upload.target=temporary-public-storage
      - name: Save mobile reports
        if: always()
        run: |
          mkdir -p lighthouse-reports/mobile
          cp -r .lighthouseci/* lighthouse-reports/mobile/ || true

      - name: Upload artifact (desktop + mobile)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: lighthouse-reports
