name: Build and deploy Node.js app to Azure Web App - witsquest

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clean and install frontend & root dependencies
        run: |
          # Clean frontend
          rm -rf frontend/node_modules frontend/package-lock.json
          npm install --prefix frontend --legacy-peer-deps --unsafe-perm
          
          # Root (for app.js)
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps

      - name: Build frontend
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_WEB_URL: ${{ secrets.VITE_WEB_URL }}
        run: npm run build --prefix frontend

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip \
            app.js \
            package.json \
            package-lock.json \
            frontend/dist

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DBB5B46D4B2D48DFB04273AC0AF60192 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E456F6CF62704855B3798479FD5A0718 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B389B2A02EBD440092802B52D7561C24 }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip -o release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'witsquest'
          slot-name: 'Production'
          package: .
